language: node_js
node_js:
  - "stable"

cache:
  directories:
    - "node_modules"

script:
  - yarn fix-node-modules
  - yarn build

deploy:
  provider: pages
  token: $GITHUB_TOKEN
  committer_from_gh: true
  skip_cleanup: true
  local_dir: build
  on:
    branch: master
