language: node_js
node_js:
  - "stable"

cache:
  directories:
    - "node_modules"

script:
  - npm run build

deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  committer-from-gh: true
  cleanup: true
  local-dir: build
  on:
    branch: master
